"""add base_key_score to beatmap

Revision ID: 67fec9fbbc6b
Revises: aebac2ac1e13
Create Date: 2023-05-15 02:53:22.890628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fec9fbbc6b'
down_revision = 'aebac2ac1e13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beatmaps',
        sa.Column('base_key_score',
            sa.Float(),
            nullable=True,
            server_default="1",
        )    
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beatmaps', 'base_key_score')
    # ### end Alembic commands ###
